# Resultados ML — Mar 2026

In [28]:
import pandas as pd

FILE_NEW = "../../analysis/results/consolidated/combined_summary_with_dispersion_2026-03-06_2028_2026-03-07_1213.csv"

df = pd.read_csv(FILE_NEW)
print(f"{len(df)} filas cargadas")
df.head(3)

88 filas cargadas

,model,r2,mse,mae,y_true,y_pred,target,dataset,sd_y_true,iqr_y_true,p_value_mae
0,DummyRegressor,-0.009368,2.428246,1.308622,"[-2.57, -1.35, 1.96, -2.4, 0.89, -1.64, 0.61, ...","[-0.06668224299065421, -0.07238317757009347, -...",sensibilidad,tmt_dprime,1.554655,2.47,1.000000
1,LinearRegression,-0.146412,2.757935,1.384453,"[-2.57, -1.35, 1.96, -2.4, 0.89, -1.64, 0.61, ...","[0.34708701316287766, 0.2291504649950749, 0.27...",sensibilidad,tmt_dprime,1.554655,2.47,0.531469
2,Ridge,0.017815,2.362854,1.278394,"[-2.57, -1.35, 1.96, -2.4, 0.89, -1.64, 0.61, ...","[-0.5086618863652304, 0.013041757137192592, 0....",sensibilidad,tmt_dprime,1.554655,2.47,0.010989

In [29]:
# sort_p = 0 para p_value < 0.001 → primeros dentro de cada dataset, ordenados solo por mae
# sort_p = p_value real para el resto → ordenados por p_value luego mae
df["sort_p"] = df["p_value_mae"].apply(lambda v: v if v >= 0.001 else 0)
df_sorted = (
    df.drop(columns=["y_true", "y_pred", "mse", "r2"])
    .sort_values(["dataset", "sort_p", "mae"])
    .drop(columns=["sort_p"])
    .reset_index(drop=True)
)

pd.set_option("display.max_rows", len(df_sorted))
df_sorted

,model,mae,target,dataset,sd_y_true,iqr_y_true,p_value_mae
0,SVR,0.076540,accuracy,tmt_accuracy,0.092552,0.16000,0.002997
1,RandomForestRegressor,0.076501,accuracy,tmt_accuracy,0.092552,0.16000,0.003996
2,Ridge,0.076361,accuracy,tmt_accuracy,0.092552,0.16000,0.006993
3,ElasticNet,0.076855,accuracy,tmt_accuracy,0.092552,0.16000,0.011988
4,XGBRegressor,0.080005,accuracy,tmt_accuracy,0.092552,0.16000,0.014985
5,Lasso,0.077222,accuracy,tmt_accuracy,0.092552,0.16000,0.019980
6,LinearRegression,0.079522,accuracy,tmt_accuracy,0.092552,0.16000,0.052947
7,DummyRegressor,0.078674,accuracy,tmt_accuracy,0.092552,0.16000,1.000000
8,SVR,6.782164,age,tmt_age,10.061504,11.00000,0.000999
9,Ridge,7.077544,age,tmt_age,10.061504,11.00000,0.000999
10,ElasticNet,7.084214,age,tmt_age,10.061504,11.00000,0.000999
11,LinearRegression,7.182260,age,tmt_age,10.061504,11.00000,0.000999
12,Lasso,7.187431,age,tmt_age,10.061504,11.00000,0.000999
13,RandomForestRegressor,7.330643,age,tmt_age,10.061504,11.00000,0.000999
14,XGBRegressor,7.612984,age,tmt_age,10.061504,11.00000,0.000999
15,DummyRegressor,7.665998,age,tmt_age,10.061504,11.00000,1.000000
16,Lasso,0.431369,c,tmt_c,0.604638,0.66000,0.000999
17,Ridge,0.431832,c,tmt_c,0.604638,0.66000,0.000999
18,ElasticNet,0.436172,c,tmt_c,0.604638,0.66000,0.000999
19,RandomForestRegressor,0.447029,c,tmt_c,0.604638,0.66000,0.000999
20,LinearRegression,0.465527,c,tmt_c,0.604638,0.66000,0.003996
21,SVR,0.449419,c,tmt_c,0.604638,0.66000,0.005994
22,XGBRegressor,0.502894,c,tmt_c,0.604638,0.66000,0.039960
23,DummyRegressor,0.455516,c,tmt_c,0.604638,0.66000,1.000000
24,Ridge,1.278394,sensibilidad,tmt_dprime,1.554655,2.47000,0.010989
25,SVR,1.294850,sensibilidad,tmt_dprime,1.554655,2.47000,0.031968
26,XGBRegressor,1.386089,sensibilidad,tmt_dprime,1.554655,2.47000,0.125874
27,RandomForestRegressor,1.310963,sensibilidad,tmt_dprime,1.554655,2.47000,0.136863
28,ElasticNet,1.310078,sensibilidad,tmt_dprime,1.554655,2.47000,0.269730
29,LinearRegression,1.384453,sensibilidad,tmt_dprime,1.554655,2.47000,0.531469
30,Lasso,1.330571,sensibilidad,tmt_dprime,1.554655,2.47000,0.670330
31,DummyRegressor,1.308622,sensibilidad,tmt_dprime,1.554655,2.47000,1.000000
32,Ridge,0.108972,eficiencia,tmt_eficiencia,0.150710,0.15000,0.002997
33,RandomForestRegressor,0.112537,eficiencia,tmt_eficiencia,0.150710,0.15000,0.005994
34,ElasticNet,0.110329,eficiencia,tmt_eficiencia,0.150710,0.15000,0.006993
35,Lasso,0.110878,eficiencia,tmt_eficiencia,0.150710,0.15000,0.011988
36,LinearRegression,0.117861,eficiencia,tmt_eficiencia,0.150710,0.15000,0.023976
37,SVR,0.109851,eficiencia,tmt_eficiencia,0.150710,0.15000,0.027972
38,XGBRegressor,0.126146,eficiencia,tmt_eficiencia,0.150710,0.15000,0.162837
39,DummyRegressor,0.113156,eficiencia,tmt_eficiencia,0.150710,0.15000,1.000000
40,LinearRegression,0.113849,FA,tmt_fa,0.137762,0.18000,0.317682
41,RandomForestRegressor,0.108166,FA,tmt_fa,0.137762,0.18000,0.399600
42,XGBRegressor,0.119417,FA,tmt_fa,0.137762,0.18000,0.599401
43,SVR,0.105026,FA,tmt_fa,0.137762,0.18000,0.756244
44,ElasticNet,0.106992,FA,tmt_fa,0.137762,0.18000,0.999001
45,DummyRegressor,0.106207,FA,tmt_fa,0.137762,0.18000,1.000000
46,Lasso,0.106207,FA,tmt_fa,0.137762,0.18000,1.000000
47,Ridge,0.106463,FA,tmt_fa,0.137762,0.18000,1.000000
48,Ridge,0.477175,K_4,tmt_k4,0.624286,0.80000,0.011988
49,ElasticNet,0.479370,K_4,tmt_k4,0.624286,0.80000,0.024975
50,Lasso,0.480604,K_4,tmt_k4,0.624286,0.80000,0.050949
51,RandomForestRegressor,0.495453,K_4,tmt_k4,0.624286,0.80000,0.064935
52,LinearRegression,0.506261,K_4,tmt_k4,0.624286,0.80000,0.080919
53,SVR,0.483465,K_4,tmt_k4,0.624286,0.80000,0.105894
54,XGBRegressor,0.525647,K_4,tmt_k4,0.624286,0.80000,0.132867
55,DummyRegressor,0.488550,K_4,tmt_k4,0.624286,0.80000,1.000000
56,XGBRegressor,0.877743,K_6,tmt_k6,1.021529,1.32500,0.077922
57,RandomForestRegressor,0.820261,K_6,tmt_k6,1.021529,1.32500,0.090909
58,SVR,0.815613,K_6,tmt_k6,1.021529,1.32500,0.539461
59,Ridge,0.811352,K_6,tmt_k6,1.021529,1.32500,0.579421
60,LinearRegression,0.887050,K_6,tmt_k6,1.021529,1.32500,0.825175
61,DummyRegressor,0.814020,K_6,tmt_k6,1.021529,1.32500,1.000000
62,Lasso,0.814020,K_6,tmt_k6,1.021529,1.32500,1.000000
63,ElasticNet,0.815014,K_6,tmt_k6,1.021529,1.32500,1.000000
64,RandomForestRegressor,0.783936,K_6,tmt_k6_v2,0.951202,1.20000,0.191808
65,LinearRegression,0.829686,K_6,tmt_k6_v2,0.951202,1.20000,0.544456
66,XGBRegressor,0.885499,K_6,tmt_k6_v2,0.951202,1.20000,0.785215
67,SVR,0.782984,K_6,tmt_k6_v2,0.951202,1.20000,0.899101
68,Ridge,0.776194,K_6,tmt_k6_v2,0.951202,1.20000,0.934066
69,DummyRegressor,0.771308,K_6,tmt_k6_v2,0.951202,1.20000,1.000000
70,Lasso,0.771308,K_6,tmt_k6_v2,0.951202,1.20000,1.000000
71,ElasticNet,0.771586,K_6,tmt_k6_v2,0.951202,1.20000,1.000000
72,XGBRegressor,0.589226,K_mean,tmt_k_mean,0.719119,0.93875,0.002997
73,RandomForestRegressor,0.573369,K_mean,tmt_k_mean,0.719119,0.93875,0.010989
74,Ridge,0.567792,K_mean,tmt_k_mean,0.719119,0.93875,0.023976
75,SVR,0.576712,K_mean,tmt_k_mean,0.719119,0.93875,0.159840
76,LinearRegression,0.614444,K_mean,tmt_k_mean,0.719119,0.93875,0.404595
77,ElasticNet,0.584856,K_mean,tmt_k_mean,0.719119,0.93875,0.458541
78,Lasso,0.585446,K_mean,tmt_k_mean,0.719119,0.93875,0.749251
79,DummyRegressor,0.579213,K_mean,tmt_k_mean,0.719119,0.93875,1.000000
80,XGBRegressor,44.357003,ssrt,tmt_ssrt,51.595577,62.25000,0.266733
81,SVR,39.914952,ssrt,tmt_ssrt,51.595577,62.25000,0.633367
82,LinearRegression,44.844277,ssrt,tmt_ssrt,51.595577,62.25000,0.928072
83,RandomForestRegressor,41.924162,ssrt,tmt_ssrt,51.595577,62.25000,0.938062
84,Ridge,40.186664,ssrt,tmt_ssrt,51.595577,62.25000,0.978022
85,DummyRegressor,40.150644,ssrt,tmt_ssrt,51.595577,62.25000,1.000000
86,ElasticNet,40.186471,ssrt,tmt_ssrt,51.595577,62.25000,1.000000
87,Lasso,40.202553,ssrt,tmt_ssrt,51.595577,62.25000,1.000000

In [30]:
SUBSET_MAP = {
    "tmt_k_mean":   "TMT ∩ CDT",
    "tmt_k4":       "TMT ∩ CDT",
    "tmt_k6":       "TMT ∩ CDT",
    "tmt_k6_v2":    "TMT ∩ CDT",
    "tmt_dprime":   "TMT ∩ GNG",
    "tmt_accuracy": "TMT ∩ GNG",
    "tmt_fa":       "TMT ∩ GNG",
    "tmt_eficiencia": "TMT ∩ GNG",
    "tmt_c":        "TMT ∩ GNG",
    "tmt_ssrt":     "TMT ∩ SST",
    "tmt_age":      "TMT",
}

df_sorted.insert(df_sorted.columns.get_loc("dataset") + 1, "Subset", df_sorted["dataset"].map(SUBSET_MAP))
df_sorted

,model,mae,target,dataset,Subset,sd_y_true,iqr_y_true,p_value_mae
0,SVR,0.076540,accuracy,tmt_accuracy,TMT ∩ GNG,0.092552,0.16000,0.002997
1,RandomForestRegressor,0.076501,accuracy,tmt_accuracy,TMT ∩ GNG,0.092552,0.16000,0.003996
2,Ridge,0.076361,accuracy,tmt_accuracy,TMT ∩ GNG,0.092552,0.16000,0.006993
3,ElasticNet,0.076855,accuracy,tmt_accuracy,TMT ∩ GNG,0.092552,0.16000,0.011988
4,XGBRegressor,0.080005,accuracy,tmt_accuracy,TMT ∩ GNG,0.092552,0.16000,0.014985
5,Lasso,0.077222,accuracy,tmt_accuracy,TMT ∩ GNG,0.092552,0.16000,0.019980
6,LinearRegression,0.079522,accuracy,tmt_accuracy,TMT ∩ GNG,0.092552,0.16000,0.052947
7,DummyRegressor,0.078674,accuracy,tmt_accuracy,TMT ∩ GNG,0.092552,0.16000,1.000000
8,SVR,6.782164,age,tmt_age,TMT,10.061504,11.00000,0.000999
9,Ridge,7.077544,age,tmt_age,TMT,10.061504,11.00000,0.000999
10,ElasticNet,7.084214,age,tmt_age,TMT,10.061504,11.00000,0.000999
11,LinearRegression,7.182260,age,tmt_age,TMT,10.061504,11.00000,0.000999
12,Lasso,7.187431,age,tmt_age,TMT,10.061504,11.00000,0.000999
13,RandomForestRegressor,7.330643,age,tmt_age,TMT,10.061504,11.00000,0.000999
14,XGBRegressor,7.612984,age,tmt_age,TMT,10.061504,11.00000,0.000999
15,DummyRegressor,7.665998,age,tmt_age,TMT,10.061504,11.00000,1.000000
16,Lasso,0.431369,c,tmt_c,TMT ∩ GNG,0.604638,0.66000,0.000999
17,Ridge,0.431832,c,tmt_c,TMT ∩ GNG,0.604638,0.66000,0.000999
18,ElasticNet,0.436172,c,tmt_c,TMT ∩ GNG,0.604638,0.66000,0.000999
19,RandomForestRegressor,0.447029,c,tmt_c,TMT ∩ GNG,0.604638,0.66000,0.000999
20,LinearRegression,0.465527,c,tmt_c,TMT ∩ GNG,0.604638,0.66000,0.003996
21,SVR,0.449419,c,tmt_c,TMT ∩ GNG,0.604638,0.66000,0.005994
22,XGBRegressor,0.502894,c,tmt_c,TMT ∩ GNG,0.604638,0.66000,0.039960
23,DummyRegressor,0.455516,c,tmt_c,TMT ∩ GNG,0.604638,0.66000,1.000000
24,Ridge,1.278394,sensibilidad,tmt_dprime,TMT ∩ GNG,1.554655,2.47000,0.010989
25,SVR,1.294850,sensibilidad,tmt_dprime,TMT ∩ GNG,1.554655,2.47000,0.031968
26,XGBRegressor,1.386089,sensibilidad,tmt_dprime,TMT ∩ GNG,1.554655,2.47000,0.125874
27,RandomForestRegressor,1.310963,sensibilidad,tmt_dprime,TMT ∩ GNG,1.554655,2.47000,0.136863
28,ElasticNet,1.310078,sensibilidad,tmt_dprime,TMT ∩ GNG,1.554655,2.47000,0.269730
29,LinearRegression,1.384453,sensibilidad,tmt_dprime,TMT ∩ GNG,1.554655,2.47000,0.531469
30,Lasso,1.330571,sensibilidad,tmt_dprime,TMT ∩ GNG,1.554655,2.47000,0.670330
31,DummyRegressor,1.308622,sensibilidad,tmt_dprime,TMT ∩ GNG,1.554655,2.47000,1.000000
32,Ridge,0.108972,eficiencia,tmt_eficiencia,TMT ∩ GNG,0.150710,0.15000,0.002997
33,RandomForestRegressor,0.112537,eficiencia,tmt_eficiencia,TMT ∩ GNG,0.150710,0.15000,0.005994
34,ElasticNet,0.110329,eficiencia,tmt_eficiencia,TMT ∩ GNG,0.150710,0.15000,0.006993
35,Lasso,0.110878,eficiencia,tmt_eficiencia,TMT ∩ GNG,0.150710,0.15000,0.011988
36,LinearRegression,0.117861,eficiencia,tmt_eficiencia,TMT ∩ GNG,0.150710,0.15000,0.023976
37,SVR,0.109851,eficiencia,tmt_eficiencia,TMT ∩ GNG,0.150710,0.15000,0.027972
38,XGBRegressor,0.126146,eficiencia,tmt_eficiencia,TMT ∩ GNG,0.150710,0.15000,0.162837
39,DummyRegressor,0.113156,eficiencia,tmt_eficiencia,TMT ∩ GNG,0.150710,0.15000,1.000000
40,LinearRegression,0.113849,FA,tmt_fa,TMT ∩ GNG,0.137762,0.18000,0.317682
41,RandomForestRegressor,0.108166,FA,tmt_fa,TMT ∩ GNG,0.137762,0.18000,0.399600
42,XGBRegressor,0.119417,FA,tmt_fa,TMT ∩ GNG,0.137762,0.18000,0.599401
43,SVR,0.105026,FA,tmt_fa,TMT ∩ GNG,0.137762,0.18000,0.756244
44,ElasticNet,0.106992,FA,tmt_fa,TMT ∩ GNG,0.137762,0.18000,0.999001
45,DummyRegressor,0.106207,FA,tmt_fa,TMT ∩ GNG,0.137762,0.18000,1.000000
46,Lasso,0.106207,FA,tmt_fa,TMT ∩ GNG,0.137762,0.18000,1.000000
47,Ridge,0.106463,FA,tmt_fa,TMT ∩ GNG,0.137762,0.18000,1.000000
48,Ridge,0.477175,K_4,tmt_k4,TMT ∩ CDT,0.624286,0.80000,0.011988
49,ElasticNet,0.479370,K_4,tmt_k4,TMT ∩ CDT,0.624286,0.80000,0.024975
50,Lasso,0.480604,K_4,tmt_k4,TMT ∩ CDT,0.624286,0.80000,0.050949
51,RandomForestRegressor,0.495453,K_4,tmt_k4,TMT ∩ CDT,0.624286,0.80000,0.064935
52,LinearRegression,0.506261,K_4,tmt_k4,TMT ∩ CDT,0.624286,0.80000,0.080919
53,SVR,0.483465,K_4,tmt_k4,TMT ∩ CDT,0.624286,0.80000,0.105894
54,XGBRegressor,0.525647,K_4,tmt_k4,TMT ∩ CDT,0.624286,0.80000,0.132867
55,DummyRegressor,0.488550,K_4,tmt_k4,TMT ∩ CDT,0.624286,0.80000,1.000000
56,XGBRegressor,0.877743,K_6,tmt_k6,TMT ∩ CDT,1.021529,1.32500,0.077922
57,RandomForestRegressor,0.820261,K_6,tmt_k6,TMT ∩ CDT,1.021529,1.32500,0.090909
58,SVR,0.815613,K_6,tmt_k6,TMT ∩ CDT,1.021529,1.32500,0.539461
59,Ridge,0.811352,K_6,tmt_k6,TMT ∩ CDT,1.021529,1.32500,0.579421
60,LinearRegression,0.887050,K_6,tmt_k6,TMT ∩ CDT,1.021529,1.32500,0.825175
61,DummyRegressor,0.814020,K_6,tmt_k6,TMT ∩ CDT,1.021529,1.32500,1.000000
62,Lasso,0.814020,K_6,tmt_k6,TMT ∩ CDT,1.021529,1.32500,1.000000
63,ElasticNet,0.815014,K_6,tmt_k6,TMT ∩ CDT,1.021529,1.32500,1.000000
64,RandomForestRegressor,0.783936,K_6,tmt_k6_v2,TMT ∩ CDT,0.951202,1.20000,0.191808
65,LinearRegression,0.829686,K_6,tmt_k6_v2,TMT ∩ CDT,0.951202,1.20000,0.544456
66,XGBRegressor,0.885499,K_6,tmt_k6_v2,TMT ∩ CDT,0.951202,1.20000,0.785215
67,SVR,0.782984,K_6,tmt_k6_v2,TMT ∩ CDT,0.951202,1.20000,0.899101
68,Ridge,0.776194,K_6,tmt_k6_v2,TMT ∩ CDT,0.951202,1.20000,0.934066
69,DummyRegressor,0.771308,K_6,tmt_k6_v2,TMT ∩ CDT,0.951202,1.20000,1.000000
70,Lasso,0.771308,K_6,tmt_k6_v2,TMT ∩ CDT,0.951202,1.20000,1.000000
71,ElasticNet,0.771586,K_6,tmt_k6_v2,TMT ∩ CDT,0.951202,1.20000,1.000000
72,XGBRegressor,0.589226,K_mean,tmt_k_mean,TMT ∩ CDT,0.719119,0.93875,0.002997
73,RandomForestRegressor,0.573369,K_mean,tmt_k_mean,TMT ∩ CDT,0.719119,0.93875,0.010989
74,Ridge,0.567792,K_mean,tmt_k_mean,TMT ∩ CDT,0.719119,0.93875,0.023976
75,SVR,0.576712,K_mean,tmt_k_mean,TMT ∩ CDT,0.719119,0.93875,0.159840
76,LinearRegression,0.614444,K_mean,tmt_k_mean,TMT ∩ CDT,0.719119,0.93875,0.404595
77,ElasticNet,0.584856,K_mean,tmt_k_mean,TMT ∩ CDT,0.719119,0.93875,0.458541
78,Lasso,0.585446,K_mean,tmt_k_mean,TMT ∩ CDT,0.719119,0.93875,0.749251
79,DummyRegressor,0.579213,K_mean,tmt_k_mean,TMT ∩ CDT,0.719119,0.93875,1.000000
80,XGBRegressor,44.357003,ssrt,tmt_ssrt,TMT ∩ SST,51.595577,62.25000,0.266733
81,SVR,39.914952,ssrt,tmt_ssrt,TMT ∩ SST,51.595577,62.25000,0.633367
82,LinearRegression,44.844277,ssrt,tmt_ssrt,TMT ∩ SST,51.595577,62.25000,0.928072
83,RandomForestRegressor,41.924162,ssrt,tmt_ssrt,TMT ∩ SST,51.595577,62.25000,0.938062
84,Ridge,40.186664,ssrt,tmt_ssrt,TMT ∩ SST,51.595577,62.25000,0.978022
85,DummyRegressor,40.150644,ssrt,tmt_ssrt,TMT ∩ SST,51.595577,62.25000,1.000000
86,ElasticNet,40.186471,ssrt,tmt_ssrt,TMT ∩ SST,51.595577,62.25000,1.000000
87,Lasso,40.202553,ssrt,tmt_ssrt,TMT ∩ SST,51.595577,62.25000,1.000000

In [31]:
df_display = df_sorted.copy()
df_display["mae"]         = df_display["mae"].round(2)
df_display["sd_y_true"]   = df_display["sd_y_true"].round(2)
df_display["iqr_y_true"]  = df_display["iqr_y_true"].round(2)
df_display["p_value_mae"] = df_display["p_value_mae"].apply(
    lambda v: "<0.001" if v < 0.001 else f"{v:.3f}"
)

df_display

,model,mae,target,dataset,Subset,sd_y_true,iqr_y_true,p_value_mae
0,SVR,0.08,accuracy,tmt_accuracy,TMT ∩ GNG,0.09,0.16,0.003
1,RandomForestRegressor,0.08,accuracy,tmt_accuracy,TMT ∩ GNG,0.09,0.16,0.004
2,Ridge,0.08,accuracy,tmt_accuracy,TMT ∩ GNG,0.09,0.16,0.007
3,ElasticNet,0.08,accuracy,tmt_accuracy,TMT ∩ GNG,0.09,0.16,0.012
4,XGBRegressor,0.08,accuracy,tmt_accuracy,TMT ∩ GNG,0.09,0.16,0.015
5,Lasso,0.08,accuracy,tmt_accuracy,TMT ∩ GNG,0.09,0.16,0.020
6,LinearRegression,0.08,accuracy,tmt_accuracy,TMT ∩ GNG,0.09,0.16,0.053
7,DummyRegressor,0.08,accuracy,tmt_accuracy,TMT ∩ GNG,0.09,0.16,1.000
8,SVR,6.78,age,tmt_age,TMT,10.06,11.00,<0.001
9,Ridge,7.08,age,tmt_age,TMT,10.06,11.00,<0.001
10,ElasticNet,7.08,age,tmt_age,TMT,10.06,11.00,<0.001
11,LinearRegression,7.18,age,tmt_age,TMT,10.06,11.00,<0.001
12,Lasso,7.19,age,tmt_age,TMT,10.06,11.00,<0.001
13,RandomForestRegressor,7.33,age,tmt_age,TMT,10.06,11.00,<0.001
14,XGBRegressor,7.61,age,tmt_age,TMT,10.06,11.00,<0.001
15,DummyRegressor,7.67,age,tmt_age,TMT,10.06,11.00,1.000
16,Lasso,0.43,c,tmt_c,TMT ∩ GNG,0.60,0.66,<0.001
17,Ridge,0.43,c,tmt_c,TMT ∩ GNG,0.60,0.66,<0.001
18,ElasticNet,0.44,c,tmt_c,TMT ∩ GNG,0.60,0.66,<0.001
19,RandomForestRegressor,0.45,c,tmt_c,TMT ∩ GNG,0.60,0.66,<0.001
20,LinearRegression,0.47,c,tmt_c,TMT ∩ GNG,0.60,0.66,0.004
21,SVR,0.45,c,tmt_c,TMT ∩ GNG,0.60,0.66,0.006
22,XGBRegressor,0.50,c,tmt_c,TMT ∩ GNG,0.60,0.66,0.040
23,DummyRegressor,0.46,c,tmt_c,TMT ∩ GNG,0.60,0.66,1.000
24,Ridge,1.28,sensibilidad,tmt_dprime,TMT ∩ GNG,1.55,2.47,0.011
25,SVR,1.29,sensibilidad,tmt_dprime,TMT ∩ GNG,1.55,2.47,0.032
26,XGBRegressor,1.39,sensibilidad,tmt_dprime,TMT ∩ GNG,1.55,2.47,0.126
27,RandomForestRegressor,1.31,sensibilidad,tmt_dprime,TMT ∩ GNG,1.55,2.47,0.137
28,ElasticNet,1.31,sensibilidad,tmt_dprime,TMT ∩ GNG,1.55,2.47,0.270
29,LinearRegression,1.38,sensibilidad,tmt_dprime,TMT ∩ GNG,1.55,2.47,0.531
30,Lasso,1.33,sensibilidad,tmt_dprime,TMT ∩ GNG,1.55,2.47,0.670
31,DummyRegressor,1.31,sensibilidad,tmt_dprime,TMT ∩ GNG,1.55,2.47,1.000
32,Ridge,0.11,eficiencia,tmt_eficiencia,TMT ∩ GNG,0.15,0.15,0.003
33,RandomForestRegressor,0.11,eficiencia,tmt_eficiencia,TMT ∩ GNG,0.15,0.15,0.006
34,ElasticNet,0.11,eficiencia,tmt_eficiencia,TMT ∩ GNG,0.15,0.15,0.007
35,Lasso,0.11,eficiencia,tmt_eficiencia,TMT ∩ GNG,0.15,0.15,0.012
36,LinearRegression,0.12,eficiencia,tmt_eficiencia,TMT ∩ GNG,0.15,0.15,0.024
37,SVR,0.11,eficiencia,tmt_eficiencia,TMT ∩ GNG,0.15,0.15,0.028
38,XGBRegressor,0.13,eficiencia,tmt_eficiencia,TMT ∩ GNG,0.15,0.15,0.163
39,DummyRegressor,0.11,eficiencia,tmt_eficiencia,TMT ∩ GNG,0.15,0.15,1.000
40,LinearRegression,0.11,FA,tmt_fa,TMT ∩ GNG,0.14,0.18,0.318
41,RandomForestRegressor,0.11,FA,tmt_fa,TMT ∩ GNG,0.14,0.18,0.400
42,XGBRegressor,0.12,FA,tmt_fa,TMT ∩ GNG,0.14,0.18,0.599
43,SVR,0.11,FA,tmt_fa,TMT ∩ GNG,0.14,0.18,0.756
44,ElasticNet,0.11,FA,tmt_fa,TMT ∩ GNG,0.14,0.18,0.999
45,DummyRegressor,0.11,FA,tmt_fa,TMT ∩ GNG,0.14,0.18,1.000
46,Lasso,0.11,FA,tmt_fa,TMT ∩ GNG,0.14,0.18,1.000
47,Ridge,0.11,FA,tmt_fa,TMT ∩ GNG,0.14,0.18,1.000
48,Ridge,0.48,K_4,tmt_k4,TMT ∩ CDT,0.62,0.80,0.012
49,ElasticNet,0.48,K_4,tmt_k4,TMT ∩ CDT,0.62,0.80,0.025
50,Lasso,0.48,K_4,tmt_k4,TMT ∩ CDT,0.62,0.80,0.051
51,RandomForestRegressor,0.50,K_4,tmt_k4,TMT ∩ CDT,0.62,0.80,0.065
52,LinearRegression,0.51,K_4,tmt_k4,TMT ∩ CDT,0.62,0.80,0.081
53,SVR,0.48,K_4,tmt_k4,TMT ∩ CDT,0.62,0.80,0.106
54,XGBRegressor,0.53,K_4,tmt_k4,TMT ∩ CDT,0.62,0.80,0.133
55,DummyRegressor,0.49,K_4,tmt_k4,TMT ∩ CDT,0.62,0.80,1.000
56,XGBRegressor,0.88,K_6,tmt_k6,TMT ∩ CDT,1.02,1.32,0.078
57,RandomForestRegressor,0.82,K_6,tmt_k6,TMT ∩ CDT,1.02,1.32,0.091
58,SVR,0.82,K_6,tmt_k6,TMT ∩ CDT,1.02,1.32,0.539
59,Ridge,0.81,K_6,tmt_k6,TMT ∩ CDT,1.02,1.32,0.579
60,LinearRegression,0.89,K_6,tmt_k6,TMT ∩ CDT,1.02,1.32,0.825
61,DummyRegressor,0.81,K_6,tmt_k6,TMT ∩ CDT,1.02,1.32,1.000
62,Lasso,0.81,K_6,tmt_k6,TMT ∩ CDT,1.02,1.32,1.000
63,ElasticNet,0.82,K_6,tmt_k6,TMT ∩ CDT,1.02,1.32,1.000
64,RandomForestRegressor,0.78,K_6,tmt_k6_v2,TMT ∩ CDT,0.95,1.20,0.192
65,LinearRegression,0.83,K_6,tmt_k6_v2,TMT ∩ CDT,0.95,1.20,0.544
66,XGBRegressor,0.89,K_6,tmt_k6_v2,TMT ∩ CDT,0.95,1.20,0.785
67,SVR,0.78,K_6,tmt_k6_v2,TMT ∩ CDT,0.95,1.20,0.899
68,Ridge,0.78,K_6,tmt_k6_v2,TMT ∩ CDT,0.95,1.20,0.934
69,DummyRegressor,0.77,K_6,tmt_k6_v2,TMT ∩ CDT,0.95,1.20,1.000
70,Lasso,0.77,K_6,tmt_k6_v2,TMT ∩ CDT,0.95,1.20,1.000
71,ElasticNet,0.77,K_6,tmt_k6_v2,TMT ∩ CDT,0.95,1.20,1.000
72,XGBRegressor,0.59,K_mean,tmt_k_mean,TMT ∩ CDT,0.72,0.94,0.003
73,RandomForestRegressor,0.57,K_mean,tmt_k_mean,TMT ∩ CDT,0.72,0.94,0.011
74,Ridge,0.57,K_mean,tmt_k_mean,TMT ∩ CDT,0.72,0.94,0.024
75,SVR,0.58,K_mean,tmt_k_mean,TMT ∩ CDT,0.72,0.94,0.160
76,LinearRegression,0.61,K_mean,tmt_k_mean,TMT ∩ CDT,0.72,0.94,0.405
77,ElasticNet,0.58,K_mean,tmt_k_mean,TMT ∩ CDT,0.72,0.94,0.459
78,Lasso,0.59,K_mean,tmt_k_mean,TMT ∩ CDT,0.72,0.94,0.749
79,DummyRegressor,0.58,K_mean,tmt_k_mean,TMT ∩ CDT,0.72,0.94,1.000
80,XGBRegressor,44.36,ssrt,tmt_ssrt,TMT ∩ SST,51.60,62.25,0.267
81,SVR,39.91,ssrt,tmt_ssrt,TMT ∩ SST,51.60,62.25,0.633
82,LinearRegression,44.84,ssrt,tmt_ssrt,TMT ∩ SST,51.60,62.25,0.928
83,RandomForestRegressor,41.92,ssrt,tmt_ssrt,TMT ∩ SST,51.60,62.25,0.938
84,Ridge,40.19,ssrt,tmt_ssrt,TMT ∩ SST,51.60,62.25,0.978
85,DummyRegressor,40.15,ssrt,tmt_ssrt,TMT ∩ SST,51.60,62.25,1.000
86,ElasticNet,40.19,ssrt,tmt_ssrt,TMT ∩ SST,51.60,62.25,1.000
87,Lasso,40.20,ssrt,tmt_ssrt,TMT ∩ SST,51.60,62.25,1.000

In [32]:
df_display = df_display.rename(columns={
    "target":       "Target",
    "Subset":       "Subset",
    "model":        "Model",
    "mae":          "MAE",
    "sd_y_true":    "SD_Target",
    "iqr_y_true":   "IQR_Target",
    "p_value_mae":  "p-value",
})

df_display

,Model,MAE,Target,dataset,Subset,SD_Target,IQR_Target,p-value
0,SVR,0.08,accuracy,tmt_accuracy,TMT ∩ GNG,0.09,0.16,0.003
1,RandomForestRegressor,0.08,accuracy,tmt_accuracy,TMT ∩ GNG,0.09,0.16,0.004
2,Ridge,0.08,accuracy,tmt_accuracy,TMT ∩ GNG,0.09,0.16,0.007
3,ElasticNet,0.08,accuracy,tmt_accuracy,TMT ∩ GNG,0.09,0.16,0.012
4,XGBRegressor,0.08,accuracy,tmt_accuracy,TMT ∩ GNG,0.09,0.16,0.015
5,Lasso,0.08,accuracy,tmt_accuracy,TMT ∩ GNG,0.09,0.16,0.020
6,LinearRegression,0.08,accuracy,tmt_accuracy,TMT ∩ GNG,0.09,0.16,0.053
7,DummyRegressor,0.08,accuracy,tmt_accuracy,TMT ∩ GNG,0.09,0.16,1.000
8,SVR,6.78,age,tmt_age,TMT,10.06,11.00,<0.001
9,Ridge,7.08,age,tmt_age,TMT,10.06,11.00,<0.001
10,ElasticNet,7.08,age,tmt_age,TMT,10.06,11.00,<0.001
11,LinearRegression,7.18,age,tmt_age,TMT,10.06,11.00,<0.001
12,Lasso,7.19,age,tmt_age,TMT,10.06,11.00,<0.001
13,RandomForestRegressor,7.33,age,tmt_age,TMT,10.06,11.00,<0.001
14,XGBRegressor,7.61,age,tmt_age,TMT,10.06,11.00,<0.001
15,DummyRegressor,7.67,age,tmt_age,TMT,10.06,11.00,1.000
16,Lasso,0.43,c,tmt_c,TMT ∩ GNG,0.60,0.66,<0.001
17,Ridge,0.43,c,tmt_c,TMT ∩ GNG,0.60,0.66,<0.001
18,ElasticNet,0.44,c,tmt_c,TMT ∩ GNG,0.60,0.66,<0.001
19,RandomForestRegressor,0.45,c,tmt_c,TMT ∩ GNG,0.60,0.66,<0.001
20,LinearRegression,0.47,c,tmt_c,TMT ∩ GNG,0.60,0.66,0.004
21,SVR,0.45,c,tmt_c,TMT ∩ GNG,0.60,0.66,0.006
22,XGBRegressor,0.50,c,tmt_c,TMT ∩ GNG,0.60,0.66,0.040
23,DummyRegressor,0.46,c,tmt_c,TMT ∩ GNG,0.60,0.66,1.000
24,Ridge,1.28,sensibilidad,tmt_dprime,TMT ∩ GNG,1.55,2.47,0.011
25,SVR,1.29,sensibilidad,tmt_dprime,TMT ∩ GNG,1.55,2.47,0.032
26,XGBRegressor,1.39,sensibilidad,tmt_dprime,TMT ∩ GNG,1.55,2.47,0.126
27,RandomForestRegressor,1.31,sensibilidad,tmt_dprime,TMT ∩ GNG,1.55,2.47,0.137
28,ElasticNet,1.31,sensibilidad,tmt_dprime,TMT ∩ GNG,1.55,2.47,0.270
29,LinearRegression,1.38,sensibilidad,tmt_dprime,TMT ∩ GNG,1.55,2.47,0.531
30,Lasso,1.33,sensibilidad,tmt_dprime,TMT ∩ GNG,1.55,2.47,0.670
31,DummyRegressor,1.31,sensibilidad,tmt_dprime,TMT ∩ GNG,1.55,2.47,1.000
32,Ridge,0.11,eficiencia,tmt_eficiencia,TMT ∩ GNG,0.15,0.15,0.003
33,RandomForestRegressor,0.11,eficiencia,tmt_eficiencia,TMT ∩ GNG,0.15,0.15,0.006
34,ElasticNet,0.11,eficiencia,tmt_eficiencia,TMT ∩ GNG,0.15,0.15,0.007
35,Lasso,0.11,eficiencia,tmt_eficiencia,TMT ∩ GNG,0.15,0.15,0.012
36,LinearRegression,0.12,eficiencia,tmt_eficiencia,TMT ∩ GNG,0.15,0.15,0.024
37,SVR,0.11,eficiencia,tmt_eficiencia,TMT ∩ GNG,0.15,0.15,0.028
38,XGBRegressor,0.13,eficiencia,tmt_eficiencia,TMT ∩ GNG,0.15,0.15,0.163
39,DummyRegressor,0.11,eficiencia,tmt_eficiencia,TMT ∩ GNG,0.15,0.15,1.000
40,LinearRegression,0.11,FA,tmt_fa,TMT ∩ GNG,0.14,0.18,0.318
41,RandomForestRegressor,0.11,FA,tmt_fa,TMT ∩ GNG,0.14,0.18,0.400
42,XGBRegressor,0.12,FA,tmt_fa,TMT ∩ GNG,0.14,0.18,0.599
43,SVR,0.11,FA,tmt_fa,TMT ∩ GNG,0.14,0.18,0.756
44,ElasticNet,0.11,FA,tmt_fa,TMT ∩ GNG,0.14,0.18,0.999
45,DummyRegressor,0.11,FA,tmt_fa,TMT ∩ GNG,0.14,0.18,1.000
46,Lasso,0.11,FA,tmt_fa,TMT ∩ GNG,0.14,0.18,1.000
47,Ridge,0.11,FA,tmt_fa,TMT ∩ GNG,0.14,0.18,1.000
48,Ridge,0.48,K_4,tmt_k4,TMT ∩ CDT,0.62,0.80,0.012
49,ElasticNet,0.48,K_4,tmt_k4,TMT ∩ CDT,0.62,0.80,0.025
50,Lasso,0.48,K_4,tmt_k4,TMT ∩ CDT,0.62,0.80,0.051
51,RandomForestRegressor,0.50,K_4,tmt_k4,TMT ∩ CDT,0.62,0.80,0.065
52,LinearRegression,0.51,K_4,tmt_k4,TMT ∩ CDT,0.62,0.80,0.081
53,SVR,0.48,K_4,tmt_k4,TMT ∩ CDT,0.62,0.80,0.106
54,XGBRegressor,0.53,K_4,tmt_k4,TMT ∩ CDT,0.62,0.80,0.133
55,DummyRegressor,0.49,K_4,tmt_k4,TMT ∩ CDT,0.62,0.80,1.000
56,XGBRegressor,0.88,K_6,tmt_k6,TMT ∩ CDT,1.02,1.32,0.078
57,RandomForestRegressor,0.82,K_6,tmt_k6,TMT ∩ CDT,1.02,1.32,0.091
58,SVR,0.82,K_6,tmt_k6,TMT ∩ CDT,1.02,1.32,0.539
59,Ridge,0.81,K_6,tmt_k6,TMT ∩ CDT,1.02,1.32,0.579
60,LinearRegression,0.89,K_6,tmt_k6,TMT ∩ CDT,1.02,1.32,0.825
61,DummyRegressor,0.81,K_6,tmt_k6,TMT ∩ CDT,1.02,1.32,1.000
62,Lasso,0.81,K_6,tmt_k6,TMT ∩ CDT,1.02,1.32,1.000
63,ElasticNet,0.82,K_6,tmt_k6,TMT ∩ CDT,1.02,1.32,1.000
64,RandomForestRegressor,0.78,K_6,tmt_k6_v2,TMT ∩ CDT,0.95,1.20,0.192
65,LinearRegression,0.83,K_6,tmt_k6_v2,TMT ∩ CDT,0.95,1.20,0.544
66,XGBRegressor,0.89,K_6,tmt_k6_v2,TMT ∩ CDT,0.95,1.20,0.785
67,SVR,0.78,K_6,tmt_k6_v2,TMT ∩ CDT,0.95,1.20,0.899
68,Ridge,0.78,K_6,tmt_k6_v2,TMT ∩ CDT,0.95,1.20,0.934
69,DummyRegressor,0.77,K_6,tmt_k6_v2,TMT ∩ CDT,0.95,1.20,1.000
70,Lasso,0.77,K_6,tmt_k6_v2,TMT ∩ CDT,0.95,1.20,1.000
71,ElasticNet,0.77,K_6,tmt_k6_v2,TMT ∩ CDT,0.95,1.20,1.000
72,XGBRegressor,0.59,K_mean,tmt_k_mean,TMT ∩ CDT,0.72,0.94,0.003
73,RandomForestRegressor,0.57,K_mean,tmt_k_mean,TMT ∩ CDT,0.72,0.94,0.011
74,Ridge,0.57,K_mean,tmt_k_mean,TMT ∩ CDT,0.72,0.94,0.024
75,SVR,0.58,K_mean,tmt_k_mean,TMT ∩ CDT,0.72,0.94,0.160
76,LinearRegression,0.61,K_mean,tmt_k_mean,TMT ∩ CDT,0.72,0.94,0.405
77,ElasticNet,0.58,K_mean,tmt_k_mean,TMT ∩ CDT,0.72,0.94,0.459
78,Lasso,0.59,K_mean,tmt_k_mean,TMT ∩ CDT,0.72,0.94,0.749
79,DummyRegressor,0.58,K_mean,tmt_k_mean,TMT ∩ CDT,0.72,0.94,1.000
80,XGBRegressor,44.36,ssrt,tmt_ssrt,TMT ∩ SST,51.60,62.25,0.267
81,SVR,39.91,ssrt,tmt_ssrt,TMT ∩ SST,51.60,62.25,0.633
82,LinearRegression,44.84,ssrt,tmt_ssrt,TMT ∩ SST,51.60,62.25,0.928
83,RandomForestRegressor,41.92,ssrt,tmt_ssrt,TMT ∩ SST,51.60,62.25,0.938
84,Ridge,40.19,ssrt,tmt_ssrt,TMT ∩ SST,51.60,62.25,0.978
85,DummyRegressor,40.15,ssrt,tmt_ssrt,TMT ∩ SST,51.60,62.25,1.000
86,ElasticNet,40.19,ssrt,tmt_ssrt,TMT ∩ SST,51.60,62.25,1.000
87,Lasso,40.20,ssrt,tmt_ssrt,TMT ∩ SST,51.60,62.25,1.000

In [33]:
df_display.to_csv("../../analysis/results/consolidated/results_mar_2026.csv", index=False)
print("Guardado.")

Guardado.