In [4]:
import pandas as pd

df = pd.read_csv('/home/gianluca/Research/datapruebas_analysis/data/raw/tmt/neuropruebas/subjects/d1875a7b-8606-4e7f-8ee1-1fc6e9bdbb2b.csv')
df.head(100)

,success,timeout,failed_images,failed_audio,failed_video,trial_type,trial_index,time_elapsed,internal_node_id,run_id,...,X_click,Y_click,T_click,position,cursor_time,remaining_items_training,remaining_items_test,data,experimental_condition,screen_id
0,True,False,[],[],[],preload,0,76,0.0-0.0,640,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,True,NaN,NaN,NaN,NaN,fullscreen,1,2993,0.0-1.0,640,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,survey-html-form,2,17856,0.0-2.0,640,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,virtual-chinrest,3,164439,0.0-3.0,640,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,instructions,4,274540,0.0-4.0,640,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,html-keyboard-response,5,275047,0.0-5.0-0.0,640,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,trail-making-test,6,300069,0.0-5.0-1.0,640,...,NaN,NaN,NaN,"[""(478.65562525489037,518.414122095456)"",""(477...","[14,29,44,62,79,96,112,129,145,164,1859,1872,1...",20.0,20.0,"[{""content"":""1"",""x"":472,""y"":664},{""content"":""2...",training,NaN
7,NaN,NaN,NaN,NaN,NaN,html-keyboard-response,7,300579,0.0-5.0-0.1,640,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,trail-making-test,8,325586,0.0-5.0-1.1,640,...,NaN,NaN,NaN,"[""(495.5993282573169,522.4008754197174)"",""(494...","[192,201,217,233,250,267,283,301,317,333,350,3...",14.0,14.0,"[{""content"":""4"",""x"":192,""y"":484},{""content"":""D...",training,NaN
9,NaN,NaN,NaN,NaN,NaN,instructions,9,334506,0.0-6.0,640,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,html-keyboard-response,10,335013,0.0-7.0-0.0,640,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,trail-making-test,11,360022,0.0-7.0-1.0,640,...,NaN,NaN,NaN,"[""(352.0761969426453,573.2319803040499)"",""(352...","[268,280,296,313,346,363,380,396,413,430,447,4...",11.0,11.0,"[{""content"":""10"",""x"":212,""y"":424},{""content"":""...",test,NaN
12,NaN,NaN,NaN,NaN,NaN,html-keyboard-response,12,360528,0.0-7.0-0.1,640,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,trail-making-test,13,385537,0.0-7.0-1.1,640,...,NaN,NaN,NaN,"[""(184.6325437421951,463.59626388686223)"",""(18...","[69,85,102,118,135,152,168,185,202,219,386,414...",13.0,13.0,"[{""content"":""D"",""x"":492,""y"":504},{""content"":""5...",test,NaN
14,NaN,NaN,NaN,NaN,NaN,html-keyboard-response,14,386043,0.0-7.0-0.2,640,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,trail-making-test,15,389805,0.0-7.0-1.2,640,...,615.0,622.0,3267.0,"[""(317.1921025258849,413.7618473335951)"",""(317...","[483,499,516,561,578,594,612,628,645,661,678,9...",19.0,19.0,"[{""content"":""2"",""x"":572,""y"":664},{""content"":""3...",test,NaN
16,NaN,NaN,NaN,NaN,NaN,html-keyboard-response,16,390311,0.0-7.0-0.3,640,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,trail-making-test,17,415324,0.0-7.0-1.3,640,...,NaN,NaN,NaN,"[""(622.178756569562,609.1127602224022)"",""(620....","[2,11,28,44,61,78,94,111,128,145,162,178,195,2...",11.0,11.0,"[{""content"":""E"",""x"":312,""y"":364},{""content"":""6...",test,NaN
18,NaN,NaN,NaN,NaN,NaN,html-keyboard-response,18,415833,0.0-7.0-0.4,640,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,trail-making-test,19,440849,0.0-7.0-1.4,640,...,NaN,NaN,NaN,"[""(340.115935999756,394.82476904335357)"",""(341...","[780,819,836,853,869,919,937,953,970,986,1003,...",3.0,3.0,"[{""content"":""18"",""x"":292,""y"":484},{""content"":""...",test,NaN
20,NaN,NaN,NaN,NaN,NaN,html-keyboard-response,20,441360,0.0-7.0-0.5,640,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,trail-making-test,21,466378,0.0-7.0-1.5,640,...,NaN,NaN,NaN,"[""(374.003342004609,362.9307424492626)"",""(374....","[115,131,148,164,181,199,259,429,443,463,476,4...",15.0,15.0,"[{""content"":""C"",""x"":152,""y"":644},{""content"":""4...",test,NaN
22,NaN,NaN,NaN,NaN,NaN,html-keyboard-response,22,466895,0.0-7.0-0.6,640,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,trail-making-test,23,489591,0.0-7.0-1.6,640,...,628.0,148.0,2378.0,"[""(602.2449883314132,624.0630851883824)"",""(602...","[226,239,255,271,288,305,322,339,356,372,388,4...",0.0,0.0,[],test,NaN
24,NaN,NaN,NaN,NaN,NaN,html-keyboard-response,24,490108,0.0-7.0-0.7,640,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,trail-making-test,25,515133,0.0-7.0-1.7,640,...,NaN,NaN,NaN,"[""(370.01658835697924,167.5798295604554)"",""(41...","[422,445,455,473,1096,1107,1123,1141,1156,1173...",5.0,5.0,"[{""content"":""H"",""x"":672,""y"":144},{""content"":""9...",test,NaN
26,NaN,NaN,NaN,NaN,NaN,html-keyboard-response,26,515641,0.0-7.0-0.8,640,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,trail-making-test,27,540666,0.0-7.0-1.8,640,...,NaN,NaN,NaN,"[""(608.2251188028578,264.25859767379364)"",""(60...","[162,206,259,272,288,306,322,339,356,373,389,4...",1.0,1.0,"[{""content"":""20"",""x"":172,""y"":329}]",test,NaN
28,NaN,NaN,NaN,NaN,NaN,html-keyboard-response,28,541176,0.0-7.0-0.9,640,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN,NaN,trail-making-test,29,566200,0.0-7.0-1.9,640,...,NaN,NaN,NaN,"[""(168.68552915167606,342.99697582795574)"",""(1...","[59,76,92,109,126,144,800,810,822,838,855,1487...",5.0,5.0,"[{""content"":""H"",""x"":372,""y"":444},{""content"":""9...",test,NaN
30,NaN,NaN,NaN,NaN,NaN,html-keyboard-response,30,566725,0.0-7.0-0.10,640,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,NaN,NaN,NaN,NaN,trail-making-test,31,591750,0.0-7.0-1.10,640,...,NaN,NaN,NaN,"[""(229.48352227803,377.88106741524274)"",""(268....","[743,756,773,789,806,823,840,856,873,889,905,9...",5.0,5.0,"[{""content"":""16"",""x"":572,""y"":184},{""content"":""...",test,NaN
32,NaN,NaN,NaN,NaN,NaN,html-keyboard-response,32,592263,0.0-7.0-0.11,640,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN,trail-making-test,33,617286,0.0-7.0-1.11,640,...,NaN,NaN,NaN,"[""(581.3145316813569,172.56327121578212)"",""(58...","[121,136,153,171,182,301,315,332,348,364,381,3...",5.0,5.0,"[{""content"":""H"",""x"":192,""y"":384},{""content"":""9...",test,NaN
34,NaN,NaN,NaN,NaN,NaN,html-keyboard-response,34,617802,0.0-7.0-0.12,640,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN,NaN,trail-making-test,35,642827,0.0-7.0-1.12,640,...,NaN,NaN,NaN,"[""(96.92396349434026,586.1889286078994)"",""(96....","[2,13,31,47,63,79,96,115,140,151,163,208,224,2...",5.0,5.0,"[{""content"":""16"",""x"":372,""y"":624},{""content"":""...",test,NaN
36,NaN,NaN,NaN,NaN,NaN,html-keyboard-response,36,643339,0.0-7.0-0.13,640,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN,NaN,trail-making-test,37,668366,0.0-7.0-1.13,640,...,NaN,NaN,NaN,"[""(503.5728355525764,529.3776937371748)"",""(503...","[121,137,154,270,287,304,320,1104,1121,1137,11...",8.0,8.0,"[{""content"":""7"",""x"":412,""y"":504},{""content"":""G...",test,NaN
38,NaN,NaN,NaN,NaN,NaN,html-keyboard-response,38,668880,0.0-7.0-0.14,640,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,NaN,NaN,NaN,NaN,trail-making-test,39,693906,0.0-7.0-1.14,640,...,NaN,NaN,NaN,"[""(546.4304372645964,488.5134721634958)"",""(547...","[84,100,117,135,182,195,212,228,246,262,279,29...",4.0,4.0,"[{""content"":""17"",""x"":332,""y"":624},{""content"":""...",test,NaN
40,NaN,NaN,NaN,NaN,NaN,html-keyboard-response,40,694421,0.0-7.0-0.15,640,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,NaN,NaN,NaN,NaN,NaN,trail-making-test,41,719450,0.0-7.0-1.15,640,...,NaN,NaN,NaN,"[""(512.5430312597434,555.2915903448737)"",""(512...","[1,22,38,143,188,206,223,245,257,272,640,655,6...",7.0,7.0,"[{""content"":""G"",""x"":612,""y"":164},{""content"":""8...",test,NaN
42,NaN,NaN,NaN,NaN,NaN,html-keyboard-response,42,719978,0.0-7.0-0.16,640,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,NaN,NaN,NaN,NaN,NaN,trail-making-test,43,745012,0.0-7.0-1.16,640,...,NaN,NaN,NaN,"[""(375.9967188284239,342.0002874968904)"",""(375...","[549,559,576,593,610,626,716,726,743,760,776,7...",9.0,9.0,"[{""content"":""12"",""x"":242,""y"":504},{""content"":""...",test,NaN
44,NaN,NaN,NaN,NaN,NaN,html-keyboard-response,44,745529,0.0-7.0-0.17,640,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,NaN,NaN,NaN,NaN,NaN,trail-making-test,45,770562,0.0-7.0-1.17,640,...,NaN,NaN,NaN,"[""(274.33450081386485,533.3644470614362)"",""(27...","[79,96,125,227,241,258,276,291,309,928,938,958...",12.0,12.0,"[{""content"":""5"",""x"":392,""y"":409},{""content"":""E...",test,NaN
46,NaN,NaN,NaN,NaN,NaN,html-keyboard-response,46,771079,0.0-7.0-0.18,640,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,NaN,NaN,NaN,NaN,NaN,trail-making-test,47,796115,0.0-7.0-1.18,640,...,NaN,NaN,NaN,"[""(372.00996518079415,312.0996375649301)"",""(37...","[242,275,292,309,325,342,358,375,712,725,745,7...",2.0,2.0,"[{""content"":""19"",""x"":632,""y"":384},{""content"":""...",test,NaN
48,NaN,NaN,NaN,NaN,NaN,html-keyboard-response,48,796632,0.0-7.0-0.19,640,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,NaN,NaN,NaN,NaN,NaN,trail-making-test,49,821668,0.0-7.0-1.19,640,...,NaN,NaN,NaN,"[""(597.261546271876,299.14268926108065)"",""(597...","[27,41,57,74,91,121,136,154,170,187,204,220,72...",15.0,15.0,"[{""content"":""C"",""x"":252,""y"":224},{""content"":""4...",test,NaN
50,NaN,NaN,NaN,NaN,NaN,survey-html-form,50,833559,0.0-8.0,640,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Uso del pad, COMENTARIOS y redireccionamiento"
51,True,NaN,NaN,NaN,NaN,fullscreen,51,834589,0.0-9.0,640,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,NaN,NaN,NaN,NaN,NaN,html-button-response,52,853175,0.0-10.0,640,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df[['position', 'cursor_time', 'x_y_clicked_position', 'trial_type']]

,position,cursor_time,x_y_clicked_position,trial_type
0,NaN,NaN,NaN,preload
1,NaN,NaN,"[111,19,1727]",fullscreen
2,NaN,NaN,"[15,14,3475]",survey-html-form
3,NaN,NaN,"[27,29,20649]",virtual-chinrest
4,NaN,NaN,NaN,instructions
5,NaN,NaN,NaN,html-keyboard-response
6,"[""(478.65562525489037,518.414122095456)"",""(477...","[14,29,44,62,79,96,112,129,145,164,1859,1872,1...",NaN,trail-making-test
7,NaN,NaN,NaN,html-keyboard-response
8,"[""(495.5993282573169,522.4008754197174)"",""(494...","[192,201,217,233,250,267,283,301,317,333,350,3...","[179,646,7008]",trail-making-test
9,NaN,NaN,NaN,instructions
10,NaN,NaN,NaN,html-keyboard-response
11,"[""(352.0761969426453,573.2319803040499)"",""(352...","[268,280,296,313,346,363,380,396,413,430,447,4...","[654,349,3254]",trail-making-test
12,NaN,NaN,NaN,html-keyboard-response
13,"[""(184.6325437421951,463.59626388686223)"",""(18...","[69,85,102,118,135,152,168,185,202,219,386,414...","[291,120,2571]",trail-making-test
14,NaN,NaN,NaN,html-keyboard-response
15,"[""(317.1921025258849,413.7618473335951)"",""(317...","[483,499,516,561,578,594,612,628,645,661,678,9...","[615,622,3267]",trail-making-test
16,NaN,NaN,NaN,html-keyboard-response
17,"[""(622.178756569562,609.1127602224022)"",""(620....","[2,11,28,44,61,78,94,111,128,145,162,178,195,2...","[458,222,5417]",trail-making-test
18,NaN,NaN,NaN,html-keyboard-response
19,"[""(340.115935999756,394.82476904335357)"",""(341...","[780,819,836,853,869,919,937,953,970,986,1003,...","[466,659,2393]",trail-making-test
20,NaN,NaN,NaN,html-keyboard-response
21,"[""(374.003342004609,362.9307424492626)"",""(374....","[115,131,148,164,181,199,259,429,443,463,476,4...","[253,246,4215]",trail-making-test
22,NaN,NaN,NaN,html-keyboard-response
23,"[""(602.2449883314132,624.0630851883824)"",""(602...","[226,239,255,271,288,305,322,339,356,372,388,4...","[628,148,2378]",trail-making-test
24,NaN,NaN,NaN,html-keyboard-response
25,"[""(370.01658835697924,167.5798295604554)"",""(41...","[422,445,455,473,1096,1107,1123,1141,1156,1173...","[469,148,4031]",trail-making-test
26,NaN,NaN,NaN,html-keyboard-response
27,"[""(608.2251188028578,264.25859767379364)"",""(60...","[162,206,259,272,288,306,322,339,356,373,389,4...","[436,588,3079]",trail-making-test
28,NaN,NaN,NaN,html-keyboard-response
29,"[""(168.68552915167606,342.99697582795574)"",""(1...","[59,76,92,109,126,144,800,810,822,838,855,1487...","[609,591,3730]",trail-making-test
30,NaN,NaN,NaN,html-keyboard-response
31,"[""(229.48352227803,377.88106741524274)"",""(268....","[743,756,773,789,806,823,840,856,873,889,905,9...","[615,660,2330]",trail-making-test
32,NaN,NaN,NaN,html-keyboard-response
33,"[""(581.3145316813569,172.56327121578212)"",""(58...","[121,136,153,171,182,301,315,332,348,364,381,3...","[458,380,2439]",trail-making-test
34,NaN,NaN,NaN,html-keyboard-response
35,"[""(96.92396349434026,586.1889286078994)"",""(96....","[2,13,31,47,63,79,96,115,140,151,163,208,224,2...","[642,569,2131]",trail-making-test
36,NaN,NaN,NaN,html-keyboard-response
37,"[""(503.5728355525764,529.3776937371748)"",""(503...","[121,137,154,270,287,304,320,1104,1121,1137,11...","[516,243,6610]",trail-making-test
38,NaN,NaN,NaN,html-keyboard-response
39,"[""(546.4304372645964,488.5134721634958)"",""(547...","[84,100,117,135,182,195,212,228,246,262,279,29...","[497,330,4669]",trail-making-test
40,NaN,NaN,NaN,html-keyboard-response
41,"[""(512.5430312597434,555.2915903448737)"",""(512...","[1,22,38,143,188,206,223,245,257,272,640,655,6...","[365,563,2562]",trail-making-test
42,NaN,NaN,NaN,html-keyboard-response
43,"[""(375.9967188284239,342.0002874968904)"",""(375...","[549,559,576,593,610,626,716,726,743,760,776,7...","[670,155,4516]",trail-making-test
44,NaN,NaN,NaN,html-keyboard-response
45,"[""(274.33450081386485,533.3644470614362)"",""(27...","[79,96,125,227,241,258,276,291,309,928,938,958...","[393,363,6065]",trail-making-test
46,NaN,NaN,NaN,html-keyboard-response
47,"[""(372.00996518079415,312.0996375649301)"",""(37...","[242,275,292,309,325,342,358,375,712,725,745,7...","[164,220,2083]",trail-making-test
48,NaN,NaN,NaN,html-keyboard-response
49,"[""(597.261546271876,299.14268926108065)"",""(597...","[27,41,57,74,91,121,136,154,170,187,204,220,72...","[388,605,2393]",trail-making-test
50,NaN,NaN,"[25,11,11726]",survey-html-form
51,NaN,NaN,NaN,fullscreen
52,NaN,NaN,NaN,html-button-response

In [13]:
df[df['trial_type'] == 'trail-making-test'][['data','experimental_condition', 'position', 'cursor_time', 'x_y_clicked_position']]

,data,experimental_condition,position,cursor_time,x_y_clicked_position
6,"[{""content"":""1"",""x"":472,""y"":664},{""content"":""2...",training,"[""(478.65562525489037,518.414122095456)"",""(477...","[14,29,44,62,79,96,112,129,145,164,1859,1872,1...",NaN
8,"[{""content"":""4"",""x"":192,""y"":484},{""content"":""D...",training,"[""(495.5993282573169,522.4008754197174)"",""(494...","[192,201,217,233,250,267,283,301,317,333,350,3...","[179,646,7008]"
11,"[{""content"":""10"",""x"":212,""y"":424},{""content"":""...",test,"[""(352.0761969426453,573.2319803040499)"",""(352...","[268,280,296,313,346,363,380,396,413,430,447,4...","[654,349,3254]"
13,"[{""content"":""D"",""x"":492,""y"":504},{""content"":""5...",test,"[""(184.6325437421951,463.59626388686223)"",""(18...","[69,85,102,118,135,152,168,185,202,219,386,414...","[291,120,2571]"
15,"[{""content"":""2"",""x"":572,""y"":664},{""content"":""3...",test,"[""(317.1921025258849,413.7618473335951)"",""(317...","[483,499,516,561,578,594,612,628,645,661,678,9...","[615,622,3267]"
17,"[{""content"":""E"",""x"":312,""y"":364},{""content"":""6...",test,"[""(622.178756569562,609.1127602224022)"",""(620....","[2,11,28,44,61,78,94,111,128,145,162,178,195,2...","[458,222,5417]"
19,"[{""content"":""18"",""x"":292,""y"":484},{""content"":""...",test,"[""(340.115935999756,394.82476904335357)"",""(341...","[780,819,836,853,869,919,937,953,970,986,1003,...","[466,659,2393]"
21,"[{""content"":""C"",""x"":152,""y"":644},{""content"":""4...",test,"[""(374.003342004609,362.9307424492626)"",""(374....","[115,131,148,164,181,199,259,429,443,463,476,4...","[253,246,4215]"
23,[],test,"[""(602.2449883314132,624.0630851883824)"",""(602...","[226,239,255,271,288,305,322,339,356,372,388,4...","[628,148,2378]"
25,"[{""content"":""H"",""x"":672,""y"":144},{""content"":""9...",test,"[""(370.01658835697924,167.5798295604554)"",""(41...","[422,445,455,473,1096,1107,1123,1141,1156,1173...","[469,148,4031]"
27,"[{""content"":""20"",""x"":172,""y"":329}]",test,"[""(608.2251188028578,264.25859767379364)"",""(60...","[162,206,259,272,288,306,322,339,356,373,389,4...","[436,588,3079]"
29,"[{""content"":""H"",""x"":372,""y"":444},{""content"":""9...",test,"[""(168.68552915167606,342.99697582795574)"",""(1...","[59,76,92,109,126,144,800,810,822,838,855,1487...","[609,591,3730]"
31,"[{""content"":""16"",""x"":572,""y"":184},{""content"":""...",test,"[""(229.48352227803,377.88106741524274)"",""(268....","[743,756,773,789,806,823,840,856,873,889,905,9...","[615,660,2330]"
33,"[{""content"":""H"",""x"":192,""y"":384},{""content"":""9...",test,"[""(581.3145316813569,172.56327121578212)"",""(58...","[121,136,153,171,182,301,315,332,348,364,381,3...","[458,380,2439]"
35,"[{""content"":""16"",""x"":372,""y"":624},{""content"":""...",test,"[""(96.92396349434026,586.1889286078994)"",""(96....","[2,13,31,47,63,79,96,115,140,151,163,208,224,2...","[642,569,2131]"
37,"[{""content"":""7"",""x"":412,""y"":504},{""content"":""G...",test,"[""(503.5728355525764,529.3776937371748)"",""(503...","[121,137,154,270,287,304,320,1104,1121,1137,11...","[516,243,6610]"
39,"[{""content"":""17"",""x"":332,""y"":624},{""content"":""...",test,"[""(546.4304372645964,488.5134721634958)"",""(547...","[84,100,117,135,182,195,212,228,246,262,279,29...","[497,330,4669]"
41,"[{""content"":""G"",""x"":612,""y"":164},{""content"":""8...",test,"[""(512.5430312597434,555.2915903448737)"",""(512...","[1,22,38,143,188,206,223,245,257,272,640,655,6...","[365,563,2562]"
43,"[{""content"":""12"",""x"":242,""y"":504},{""content"":""...",test,"[""(375.9967188284239,342.0002874968904)"",""(375...","[549,559,576,593,610,626,716,726,743,760,776,7...","[670,155,4516]"
45,"[{""content"":""5"",""x"":392,""y"":409},{""content"":""E...",test,"[""(274.33450081386485,533.3644470614362)"",""(27...","[79,96,125,227,241,258,276,291,309,928,938,958...","[393,363,6065]"
47,"[{""content"":""19"",""x"":632,""y"":384},{""content"":""...",test,"[""(372.00996518079415,312.0996375649301)"",""(37...","[242,275,292,309,325,342,358,375,712,725,745,7...","[164,220,2083]"
49,"[{""content"":""C"",""x"":252,""y"":224},{""content"":""4...",test,"[""(597.261546271876,299.14268926108065)"",""(597...","[27,41,57,74,91,121,136,154,170,187,204,220,72...","[388,605,2393]"

In [14]:
content1 = [{"content":"4","x":192,"y":484},{"content":"D","x":332,"y":364},{"content":"5","x":252,"y":444},{"content":"E","x":192,"y":529},{"content":"6","x":332,"y":404},{"content":"F","x":512,"y":504},{"content":"7","x":652,"y":344},{"content":"G","x":532,"y":204},{"content":"8","x":472,"y":124},{"content":"H","x":592,"y":284},{"content":"9","x":492,"y":204},{"content":"I","x":432,"y":104},{"content":"10","x":332,"y":264},{"content":"J","x":232,"y":284}]

In [16]:
content1

[{'content': '4', 'x': 192, 'y': 484},
 {'content': 'D', 'x': 332, 'y': 364},
 {'content': '5', 'x': 252, 'y': 444},
 {'content': 'E', 'x': 192, 'y': 529},
 {'content': '6', 'x': 332, 'y': 404},
 {'content': 'F', 'x': 512, 'y': 504},
 {'content': '7', 'x': 652, 'y': 344},
 {'content': 'G', 'x': 532, 'y': 204},
 {'content': '8', 'x': 472, 'y': 124},
 {'content': 'H', 'x': 592, 'y': 284},
 {'content': '9', 'x': 492, 'y': 204},
 {'content': 'I', 'x': 432, 'y': 104},
 {'content': '10', 'x': 332, 'y': 264},
 {'content': 'J', 'x': 232, 'y': 284}]