# Comparación: Análisis Gus vs Últimas corridas

In [20]:
import pandas as pd
from pathlib import Path

BASE = Path('/home/gianluca/Research/datapruebas_analysis')
GUS_DIR = BASE / 'analysis 27-01 gus'

tasks = {
    'SST': ('2026-01-27_19-53-13', 'sst_analysis.csv', 'sst_analysis'),
    'CDT': ('2026-01-27_19-53-16', 'cdt_analysis.csv', 'cdt_analysis'),
    'Go/No-Go': ('2026-01-27_19-53-18', 'gonogo_analysis.csv', 'gonogo_analysis')
}

In [21]:
# Cargar todos los dataframes
dfs = {}
for name, (gus_ts, filename, data_dir) in tasks.items():
    latest_dir = sorted((BASE / 'data' / data_dir).iterdir())[-1]
    dfs[name] = {
        'gus': pd.read_csv(GUS_DIR / gus_ts / filename).sort_values('subject_id').reset_index(drop=True),
        'latest': pd.read_csv(latest_dir / filename).sort_values('subject_id').reset_index(drop=True),
        'latest_dir': latest_dir.name
    }
    print(f"{name}: Gus={len(dfs[name]['gus'])} | Latest={len(dfs[name]['latest'])} ({latest_dir.name})")

SST: Gus=246 | Latest=246 (2026-01-29_10-00-12)
CDT: Gus=248 | Latest=248 (2026-01-29_10-00-17)
Go/No-Go: Gus=310 | Latest=310 (2026-01-29_10-00-21)

In [22]:
# Comparar (deben ser idénticos excepto por el orden)
for name, data in dfs.items():
    gus, latest = data['gus'], data['latest']
    diff = gus.compare(latest)
    
    print(f"=== {name} ===")
    if diff.empty:
        print("Idénticos ✓\n")
    else:
        print("Diferencias encontradas:")
        display(diff)

=== SST ===
Idénticos ✓

=== CDT ===
Idénticos ✓

=== Go/No-Go ===
Idénticos ✓

## TMT

In [29]:
# Cargar TMT
tmt_gus = pd.read_csv(GUS_DIR / '2026-01-27_17-00-02' / 'analysis.csv').sort_values(['subject_id', 'trial_order_of_appearance']).reset_index(drop=True)
latest_tmt_dir = sorted((BASE / 'data' / 'hand_analysis').iterdir())[-1]
tmt_latest = pd.read_csv(latest_tmt_dir / 'analysis.csv').sort_values(['subject_id', 'trial_order_of_appearance']).reset_index(drop=True)

print(f"TMT: Gus={len(tmt_gus)} | Latest={len(tmt_latest)} ({latest_tmt_dir.name})")

TMT: Gus=7508 | Latest=7508 (2026-01-26_12-43-25)

In [30]:
# Ordenar columnas y comparar
tmt_latest_reord = tmt_latest[tmt_gus.columns]
diff = tmt_gus.compare(tmt_latest_reord)

if diff.empty:
    print("TMT: Idénticos ✓")
else:
    print(f"TMT: {len(diff)} filas con diferencias")
    display(diff)

TMT: 1563 filas con diferencias

     non_cut_area_difference_from_ideal               \
                                   self        other
6                            681.401600   681.401600
25                                  NaN          NaN
28                           772.164719   772.164719
31                                  NaN          NaN
34                          3145.467447  3145.467447
...                                 ...          ...
7485                        2398.291371  2398.291371
7486                                NaN          NaN
7493                                NaN          NaN
7494                         958.716851   958.716851
7497                                NaN          NaN

     area_difference_from_ideal
                           self        other
6                    541.076689   541.076689
25                   689.190810   689.190810
28                          NaN          NaN
31                  1437.403749  1437.403749
34                          NaN          NaN
...                         ...          ...
7485                2973.975728  2973.975728
7486                 595.152919   595.152919
7493                1296.961208  1296.961208
7494                        NaN          NaN
7497                1405.264422  1405.264422

[1563 rows x 4 columns]

In [32]:
diff

     non_cut_area_difference_from_ideal               \
                                   self        other
6                            681.401600   681.401600
25                                  NaN          NaN
28                           772.164719   772.164719
31                                  NaN          NaN
34                          3145.467447  3145.467447
...                                 ...          ...
7485                        2398.291371  2398.291371
7486                                NaN          NaN
7493                                NaN          NaN
7494                         958.716851   958.716851
7497                                NaN          NaN

     area_difference_from_ideal
                           self        other
6                    541.076689   541.076689
25                   689.190810   689.190810
28                          NaN          NaN
31                  1437.403749  1437.403749
34                          NaN          NaN
...                         ...          ...
7485                2973.975728  2973.975728
7486                 595.152919   595.152919
7493                1296.961208  1296.961208
7494                        NaN          NaN
7497                1405.264422  1405.264422

[1563 rows x 4 columns]